param(
    [Parameter(Mandatory=$true)][string]$EnvironmentUrl,
    [string]$SolutionName = "AIInvoiceProcessingAutomation"
)

$ErrorActionPreference = "Stop"
Write-Host "Authenticating to $EnvironmentUrl"
pac auth create --environment $EnvironmentUrl
pac solution clone --name $SolutionName --outputDirectory ./solution/exported
Write-Host "Solution cloned to ./solution/exported. Commit the YAML source generated by Dataverse." 
